name: Deploy Docker Secret

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
  DOCKER_SECRET_NAME: docker.secret
  DOCKER_SERVER: https://index.docker.io/v1/
  DOCKER_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
  DOCKER_EMAIL: ${{ secrets.CONTAINER_REGISTRY_EMAIL }}
  DEPLOYMENT_NAMESPACE: dev
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${KUBECONFIG}" > ~/.kube/config

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Create Docker Secret
        run: kubectl create secret docker-registry ${{ env.DOCKER_SECRET_NAME }} --namespace=${{ env.DEPLOYMENT_NAMESPACE }} --docker-server=${{ env.DOCKER_SERVER }} --docker-username=${{ env.DOCKER_USERNAME }} --docker-password=${{ env.DOCKER_PASSWORD }} --docker-email=${{ env.DOCKER_EMAIL }}